version: "3.9"

services:
  api:
    image: sistema-recomendacao:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistema-recomendacao-api
    ports:
      - "8000:8000"
    restart: unless-stopped
